DEBUG = True
TESTING = False
TOKEN_KEY = "vangaynaodokhimuachangroingaynaodokhitraidatthoixoayvong"
SUPABASE_URL = 'https://fqkdmrlklhtnzjrmwcse.supabase.co'
SUPABASE_API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxa2RtcmxrbGh0bnpqcm13Y3NlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5ODc3NDM3MywiZXhwIjoyMDE0MzUwMzczfQ.zm3A9VnZVLyEssQelVcC7jrV-lXagmAnIjHbXJcoMJE'